coffee_all = [
    {"type": "cappuccino", "stock": 1, "ranking": 1},
    {"type": "espresso", "stock": 2, "ranking": 5},
    {"type": "caffè mocha", "stock": 3, "ranking": 3},
    {"type": "latte", "stock": 4, "ranking": 1},
    {"type": "americano", "stock": 5, "ranking": 2},
    {"type": "flat white", "stock": 6, "ranking": 8},
    {"type": "caffè macchiato", "stock": 7, "ranking": 1},
    {"type": "cortado", "stock": 8, "ranking": 4},
    {"type": "café au lait", "stock": 9, "ranking": 1},
    {"type": "cold brew", "stock": 10, "ranking": 6},
    {"type": "iced coffee", "stock": 11, "ranking": 8},
    {"type": "irish coffee", "stock": 12, "ranking": 7},
    {"type": "ristretto", "stock": 13, "ranking": 4},
    {"type": "frappe", "stock": 14, "ranking": 1},
    {"type": "doppio", "stock": 15, "ranking": 1},
    {"type": "coffea arabica", "stock": 16, "ranking": 2},
    {"type": "lungo", "stock": 17, "ranking": 4},
    {"type": "red Eye", "stock": 18, "ranking": 3},
    {"type": "long red", "stock": 19, "ranking": 1},
    {"type": "black", "stock": 20, "ranking": 9},
]
